version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  catalog-svc:
    user: api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /start.sh
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - .:/home/api/app
      - static_volume:/home/api/app/static
    environment:
      DJANGO_SETTINGS_MODULE: main.settings.dev
      DJANGO_DEBUG: "on"
      SECRET_KEY: your-secret-key
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
