version: '3.8'

networks:
  fc:
    name: fc-network
    driver: bridge

volumes:
  pgdata:
  static_volume:

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default
      - fc

  redis:
    image: redis:alpine
    networks:
      - default
      - fc

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - default
      - fc

  celery:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    command: /home/api/start-celery.sh
    volumes:
      - .:/home/api/app
    container_name: celery
    environment:
      DJANGO_SETTINGS_MODULE: main.settings.dev
      DJANGO_DEBUG: "on"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY: your-secret-key
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
      AMQP_URI: amqp://guest:guest@rabbitmq/
      EXCHANGE: catalog_videos
      EXCHANGE_DLX: catalog_videos_dlx
      CATALOG_VIDEOS_DEAD: catalog_videos_created_dead
      CATALOG_VIDEOS_DEAD_RK: catalog_videos_created.dead
      CATALOG_VIDEOS: catalog_videos_created
      CATALOG_VIDEOS_RK: catalog_videos_created
    depends_on:
      - redis
      - catalog-svc
      - rabbitmq
    networks:
      - default
      - fc

  catalog-svc:
    user: api
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    command: /home/api/start.sh
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - .:/home/api/app
      - static_volume:/home/api/app/static
    environment:
      DJANGO_SETTINGS_MODULE: main.settings.dev
      DJANGO_DEBUG: "on"
      SECRET_KEY: your-secret-key
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
      AMQP_URI: amqp://guest:guest@rabbitmq/
      EXCHANGE: catalog_videos
      EXCHANGE_DLX: catalog_videos_dlx
      CATALOG_VIDEOS_DEAD: catalog_videos_created_dead
      CATALOG_VIDEOS_DEAD_RK: catalog_videos_created.dead
      CATALOG_VIDEOS: catalog_videos_created
      CATALOG_VIDEOS_RK: catalog_videos_created
    networks:
      - default
      - fc
