FROM python:3.10.2-slim

RUN apt update && \
    apt install -y --no-install-recommends \
    build-essential \
    python3-dev \
    libffi-dev  \
    libssl-dev \
    libpcre3-dev \
    zlib1g-dev \
    libtiff5-dev \
    libbz2-dev \
    apt-utils \
    vim \
    default-jre \
    git \
    zsh \
    curl \
    wget \
    fonts-powerline \
    libpq-dev


RUN useradd -ms /bin/zsh api
USER api:api
WORKDIR /home/api/app

## virtualenv
ENV VIRTUAL_ENV=/home/api/venv \
    PATH="$VIRTUAL_ENV/bin:$PATH" \
    PATH=$PATH:/home/api/.local/bin \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=${PYTHONPATH}/home/api/app/ \
    LIBRARY_PATH=/lib:/usr/lib \
    JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

COPY ./requirements .

RUN python3 -m venv $VIRTUAL_ENV && \
    pip install --upgrade pip && \
    pip install -r dev.txt && \
    sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.2/zsh-in-docker.sh)" -- \
    -t "ys" \
    -p git \
    -p git-flow \
    -p https://github.com/zsh-users/zsh-completions \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zdharma/fast-syntax-highlighting \
    -a "export TERM=xterm-256color" && \
    echo '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh' >> ~/.zshrc

COPY --chown=api:api ./.devcontainer/entrypoint.sh /home/api/app/entrypoint.sh
COPY --chown=api:api ./.devcontainer/start.sh /home/api/app/start.sh
COPY --chown=api:api ./.devcontainer/gitconfig /home/api/.gitconfig


EXPOSE 5000
ENTRYPOINT [ "/home/api/app/entrypoint.sh" ]

