version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: redis
  celery:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    command: /home/api/start-celery.sh
    volumes:
      - .:/home/api/app
    container_name: celery
    environment:
      DJANGO_SETTINGS_MODULE: main.settings.dev
      DJANGO_DEBUG: "on"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY: your-secret-key
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
    depends_on:
      - redis
      - catalog-svc
  catalog-svc:
    user: api
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    command: /home/api/start.sh
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - .:/home/api/app
      - static_volume:/home/api/app/static
    environment:
      DJANGO_SETTINGS_MODULE: main.settings.dev
      DJANGO_DEBUG: "on"
      SECRET_KEY: your-secret-key
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
