# Generated by Django 4.0.4 on 2022-04-30 14:34

import apps.videos.views
from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("genres", "0001_initial"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="title",
                        verbose_name="slug",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "year_launched",
                    models.PositiveSmallIntegerField(verbose_name="Year launched"),
                ),
                ("opened", models.BooleanField(default=False, verbose_name="Opened")),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("F", "Free"),
                            ("10", "Ten years old"),
                            ("12", "Twelve years old"),
                            ("14", "Fourteen years old"),
                            ("16", "Sixteen years old"),
                            ("18", "Eighteen years old"),
                        ],
                        default="F",
                        max_length=2,
                        verbose_name="Rating",
                    ),
                ),
                ("duration", models.PositiveSmallIntegerField(verbose_name="Duration")),
                (
                    "thumb_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.videos.views.thumb_upload_to_path,
                    ),
                ),
                (
                    "banner_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.videos.views.banner_upload_to_path,
                    ),
                ),
                (
                    "trailer_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.videos.views.trailer_upload_to_path,
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.videos.views.video_upload_to_path,
                    ),
                ),
                ("categories", models.ManyToManyField(to="categories.category")),
                ("genres", models.ManyToManyField(to="genres.genre")),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "ordering": ["created"],
            },
        ),
    ]
