# Generated by Django 3.2.6 on 2021-12-03 15:09

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CastMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "kind",
                    models.IntegerField(
                        choices=[(0, "Director"), (1, "Actor")],
                        default=1,
                        verbose_name="Kind",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cast Member",
                "verbose_name_plural": "Cast Members",
                "ordering": ["created"],
            },
        ),
        migrations.AddIndex(
            model_name="castmember",
            index=models.Index(fields=["code"], name="castmembers_code_6ab51f_idx"),
        ),
    ]
